spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:mysql://localhost:3306/tasklist
    username: mysql
    password: ingested 
    driver-class-name: com.mysql.cj.jdbc.Driver
    #initialization-mode: always